# Generated by Django 4.1.2 on 2023-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Status', models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=400)),
                ('User', models.CharField(max_length=500)),
            ],
        ),
    ]
